name: "multiperl test"
on:
  push:
    branches: "*"
    tags-ignore: "*"
  pull_request: ~

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Build archive
        uses: rjbs/dzil-build@main

  multiperl-test:
    needs: build-tarball
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [ "devel", "5.38", "5.36", "5.34", "5.32", "5.30", "5.28", "5.26", "5.24", "5.22", "5.20" ]

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - name: Test distribution
        uses: rjbs/test-perl-dist@main
