name: "multiperl test"
on:
  workflow_dispatch: ~
  push:
    branches: "*"
    tags-ignore: "*"
  pull_request: ~

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.build-archive.outputs.perl-versions }}
    steps:
    - name: Build archive
      id: build-archive
      uses: rjbs/dzil-build@v0

  multiperl-test:
    needs: build-tarball
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.build-tarball.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
    - name: Test distribution
      uses: rjbs/test-perl-dist@v0
